replicaCount: 2

image:
  repository: aksclusteregistry.azurecr.io/fastapiapp  # 🔹 Your ACR image repo
  tag: v1                                               # 🔹 Change for new versions
  pullPolicy: IfNotPresent

containerPort: 8000

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Optional environment variables for your app
env:
  - name: ENVIRONMENT
    value: "production"
  - name: APP_NAME
    value: "FastAPI App on AKS"
